name = "prisma-accelerate-workers"
main = "src/index.ts"
minify = true
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[placement]
mode = "smart"

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "dfb1cb13fcaf4899a624d03a63946e51"

# [vars]
# SECRET = "****"
